name: deploy

on:
  push:
  workflow_dispatch:
  schedule:
    # 这是UTC时间，+8:00后是北京时间
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: build
        run: hugo

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.ACTION_TOKEN }}
          EXTERNAL_REPOSITORY: yuanwangshijie/yuanwangshijie.github.io
          PUBLISH_BRANCH: main
          PUBLISH_DIR: ./public
          commit_message: ${{ github.event.head_commit.message }}
